dist: precise
language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
before_install:
- composer self-update
install: travis_retry composer install --no-interaction --prefer-dist
script:
- composer tests-travis
notifications:
  slack:
    rooms:
      secure: cXK5N6oodFue5ohqlJxxs1SltKmnKp9AZ5gw3+t7moMV2QPSHkAGn48VdDsYpu5uOg35f61FH+dnAXqQ1kZXMj5YBZRmcwEAePy15mesle2u14P4MrAmFkc4Qd/9a9GxtCgcv6blcjwuyk6ZAhxbX8ZYrrIINRFRyLHz2SKIQjhxjBeyGCaFpOHXzJrjhOxmhX4VWbncWYHyh2UCb+j70OhYY5bnZtn3vAKdff1y+WxCrAsspy2Aw53HKR/hQptYsKWp4KWLPvO1LgKAEYVtV9v5abO3x/o7skcF0nmIFzyx7NJlV598DIXNaw68goKx//jnDTFZkPEH1qS/ldWekDIo8ZeKhgs+xExaDNBCDQ+fW923swIw8pjnFcPLasgWUJl0HPumchRrpdIu4YWLNTs7bwM8LJfsAIyE8ng/9xQTsi2RU2CH3mvU+EYmLd71WBdKbTe3EA26w5tMgjZCyrxO8GWzjQCvpnUzomI2JBYVMzGmlP8FngDn0eydsJfhsq7ygqleNV2dyvd6MXxo+C199RFjWaJl6Dst8o1vrl+tEwr+OKW24R8Ydm3anHkLyh2gTRLopzbBF1CcyvWKG/e5ytbY4t0IEVmQVhriLoOOJSCbpaGBbBysL1MxfJnrVDvGlvurVrDc9vKR3JDA2Oiqhs3hvXT1JjWKL2WGHIg=
