dist: xenial
language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
before_install:
- composer self-update
install: travis_retry composer install --no-interaction --prefer-dist
script:
- composer tests-travis
notifications:
  slack:
    rooms:
      secure: cXK5N6oodFue5ohqlJxxs1SltKmnKp9AZ5gw3+t7moMV2QPSHkAGn48VdDsYpu5uOg35f61FH+dnAXqQ1kZXMj5YBZRmcwEAePy15mesle2u14P4MrAmFkc4Qd/9a9GxtCgcv6blcjwuyk6ZAhxbX8ZYrrIINRFRyLHz2SKIQjhxjBeyGCaFpOHXzJrjhOxmhX4VWbncWYHyh2UCb+j70OhYY5bnZtn3vAKdff1y+WxCrAsspy2Aw53HKR/hQptYsKWp4KWLPvO1LgKAEYVtV9v5abO3x/o7skcF0nmIFzyx7NJlV598DIXNaw68goKx//jnDTFZkPEH1qS/ldWekDIo8ZeKhgs+xExaDNBCDQ+fW923swIw8pjnFcPLasgWUJl0HPumchRrpdIu4YWLNTs7bwM8LJfsAIyE8ng/9xQTsi2RU2CH3mvU+EYmLd71WBdKbTe3EA26w5tMgjZCyrxO8GWzjQCvpnUzomI2JBYVMzGmlP8FngDn0eydsJfhsq7ygqleNV2dyvd6MXxo+C199RFjWaJl6Dst8o1vrl+tEwr+OKW24R8Ydm3anHkLyh2gTRLopzbBF1CcyvWKG/e5ytbY4t0IEVmQVhriLoOOJSCbpaGBbBysL1MxfJnrVDvGlvurVrDc9vKR3JDA2Oiqhs3hvXT1JjWKL2WGHIg=
env:
  global:
    secure: YJ9AnwZQi5t29pZgz/M732iX0oPSSozv/KTRa5COIY+bTt6MqIFuM4k4RjBn58yxbjJv6SX2+m0q3uIDX06gZp2FnxJdqLa/KODcjNZkiQ8QHCBdfmAsmKpUdh1Obo7R2VW469/uMHUk+LQL8EpyFQIQ8i2nxPOpGreA+3H7dnLIf7L1H1wCsXs9WRh8cDdCbqHUHwYmBWe3rzmch9wgeucU5FVNAI60N3RYzGCihcxhdM5f6z5iwRsS9ZwcTzvrUCIm19nRzKMj03FtBKfteUdTOtpIbxqumOp8or+fbf7b2dnC0uLG0rdlnDgSYW7puVQMRJazn5dOBGBV6t5Wy9xYlwotJe9XT+NrBtE+Wi97MDEB/r0fkeZU09rAktOHmyN4NzalWH2ysaeQfDVhzZFgeJkBjkXqMgXPF9nSwqZrZMqVvWPrc4mFwpUYAAokZ/gMWuvnie4FzvG8aVwo+WQgy2FqtrkWOmdAX4AHkYBCMJFGLR495tuT+yvCEHquqAZk9TKBOSnFLRBXb5FpcT0Yj8kw0DDTwDB7fFnr9nzy+3xxgNyEEk+eJldUUMCG1IPoggKOKQtUqxaOGGp4MbRit5kz4KkuRdKmKh4U/SA96K1gBvDGNtRZal1D2X0EB3TwOJN1V9TZHISTnxe6r1IcUfhij034yslaQP3eMME=
